
import sys
import logging
from argparse import ArgumentParser, RawTextHelpFormatter

from lib.SegCounter import alignAndCount


description = \
    "Description:\n\n" + \
    "This subcommand pseudo-aligns reads (single or paired-end) into the segments and obtain " + \
    "segment (single or segment-pair) counts."
parser = ArgumentParser(description=description, formatter_class=RawTextHelpFormatter,
                        add_help=False)
parser.add_argument("-ref", "--segs-ref-file", help="specify the segments reference FASTA file (generated by genSegs subcommand)",
                    required=True)
parser.add_argument("-o", "--output-file", help="specify output filename", required=True)
parser.add_argument("-cmd1", "--align-command1", help="specify the alignment command to pseudo-align reads to segments", required=True)
parser.add_argument("-cmd2", "--align-command2", help="specify the alignment command to pseudo-align second-end in" + \
                    "paired-end reads to segments", required=False)


def main():
    args = parser.parse_args()

    # Setting logging preferences
    logger = logging.getLogger(__name__)

    alignAndCount(args.segs_ref_file, args.output_file, args.align_command1, args.align_command2)
    
if __name__ == '__main__':
    main()
